### ISSUE TITLE
Add test

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/termchat#21]
What do you think about:

https://github.com/lemunozm/termchat/commit/1dec2d76b5fbd0cc4d86a7edc5d28cb01aca5f33

One issue remains sometime it sends the input twice so the test fail

**Comment by lemunozm** [comment]
I like it! 
I thought that create tests for `termchat` should be really difficult but it seems simpler :)

I left some comments, but I like a lot the idea.

**Comment by lemunozm** [comment]
https://github.com/lemunozm/termchat/pull/22
