### ISSUE TITLE
Add asciivideo

### ISSUE THREAD

**Issue by lemunozm** [lemunozm/termchat#26]
Integrate https://github.com/sigmaSd/term_cam in `termchat`

Regarding the last conversation in https://github.com/lemunozm/termchat/issues/23, I think that the video will appears and the normal conversation should be available. So a right panel with the cams could be enough (I think also this can be the easier implementation). Using `tui-rs` blocs, each video can have a pretty border with the user name.

**Comment by sigmaSd** [comment]
https://github.com/lemunozm/termchat/compare/master...sigmaSd:integrate_video?expand=1

The performance in release mode is acceptable.

I did not test with multiple stream, theoretically it should work.

**Comment by lemunozm** [comment]
I love it!!!

Do you want to make it a PR?

**Comment by sigmaSd** [comment]
Yes , should I remove minifb (as I did above) or keep it as an alternative?

**Comment by lemunozm** [comment]
mmm... I like more to have all features in an *ascii* ecosystem. I would prefer to change it.
Thanks!!

**Comment by sigmaSd** [comment]
I feel the same!
