### ISSUE TITLE
Android is not able to send hellolan message?

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/termchat#27]
termchat works on termux https://wiki.termux.com/wiki/Main_Page very well.

One small issue is if you run the  termchat instance in android before the peer one, no communication happens, if you start termchat on termux second (after opening a peer termchat instance in the pc for example) everything works correctly.

to reproduce:
1- open termchat in andorid (via termux)
2 - open termchat in pc  -> no communication happens
..
3- close termchat on android then reopen it -> now communication is established

**Comment by lemunozm** [comment]
mmm... it is possible that some layer (termux or android itself) blocks the UDP multicast message. I will investigate it. 

Also, for better robustness, I want to make term chat able to send more than one hellolan multicast message, it relatively easy that a UDP packet gets lost. If this happens that instance will not find others.

**Comment by sigmaSd** [comment]
I think the problem lies in message-io interaction with android because I can reproduce the same bug only using message-io, you can try https://github.com/sigmaSd/AndroChat

**Comment by lemunozm** [comment]
Thanks for the point

**Comment by lemunozm** [comment]
Hi @sigmaSd, could you confirm if android devices use 32 bits?

**Comment by sigmaSd** [comment]
Hi,

No, the phone I'm testing with is aarch64.

I retried with master branch of message-io and multicast example its still the same issue.

The pc gets notified when android connects, but android doesn't get notified about any other peer connection.

As far as I can tell android multicast might need some special handling https://stackoverflow.com/questions/4589946/problem-with-multicastsocket-on-java-android

For example "CHANGE_WIFI_MULTICAST_STATE" permission which I doubt termux have out of the box.

Also this looks interesting https://github.com/godotengine/godot/issues/24666

I'll close this for now, if I have more info I'll report back.

**Comment by lemunozm** [comment]
Thanks, @sigmaSd, I had an issue registering the sockets in the 32 bits OS poll, and maybe it was related. But the link you have shared seems to point to the problem.
