### ISSUE TITLE
[Discussion] User interaction design.

### ISSUE THREAD

**Issue by andrew-ares** [lemunozm/termchat#36]
The user may accidentally touch the esc key during input and cause unexpected exit. 
On the other hand,  would it be more ergonomic if the default interface is a chat room when you open the program, and the input box opens when the `/` key is pressed(Just like [bottom](https://github.com/ClementTsang/bottom) handles process search)?

**Comment by lemunozm** [comment]
I agree with checking the exit. Maybe a pop-up verifying the exit by the user. (Something similar when you exit from vim/emacs without saves). Thanks for the suggestion :)

Regarding the second part, what is the gain of hiding the input box from the user, and force them to press `/`? As a chat program, it is expected you want to write something in most cases. The search of `bottom` has sense because you only want to write if you are going to search, probably in few cases.

**Comment by andrew-ares** [comment]
That makes sense, it seems unnecessary to hide the input box by default for a chat program. 
I thought of this because maybe we can introduce widget focus to specialize the events under each widget. When the LAN room has focus, it will have a highlight style and we can select the message with the up and down keys or even the mouse, and then choose to reply to the message, just like a modern chat app :)

**Comment by lemunozm** [comment]
I like that. It's true that at this moment there is almost "nothing" selectable in the window and you can mapping everything at once. But in the future, you could move the focus over it with `<tab>` or `Ctrl+<key>` for example. 

I do not know if you have used vim. But maybe could be cool to add a *vim mode* that implements something similar to press `<ESC>` to enable moving along the chat and press `i` you enter the focus in the input box to write.

**Comment by andrew-ares** [comment]
> But in the future, you could move the focus over it with `<tab>` or `Ctrl+<key>` for example.

Or a mouse click :) But AFAIK, windows terminal does not support mouse input: [microsoft/terminal#376](https://github.com/microsoft/terminal/issues/376). So it is necessary to reserve a key to switch focus.  If there are not too many widgets in the future, for convenience, `<tab>`  may be a good option.


> But maybe could be cool to add a vim mode that implements something similar to press `<ESC>` to enable moving along 
> the chat and press `I` you enter the focus in the input box to write.

This is cool and should be relatively easy to implement.
