### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by ghost** [lemunozm/termchat#55]
It worked at first, but after about ~5 minutes `Termchat: Connection refused` was displayed and no connection could be established.

How is this debuggable?

We are on a semi-public network (managed student housing network).

**Comment by lemunozm** [comment]
Hi, what are you doing exactly? Could you share reproducible steps? I used termchat for more than 5 minutes and I do not get the error you say.

**Comment by ghost** [comment]
I suppose it has something to do with the network I'm in. Have to debug myself.
