### ISSUE TITLE
Handle utf8 correctly 

### ISSUE THREAD

**Issue by sigmaSd** [lemunozm/termchat#8]
Currently only ascii is handled correctly.
This https://github.com/lemunozm/termchat/blob/master/src/state.rs#L107 will panic with any charcter that has a length > 1.

An easy way to fix is this is to use a `Vec<char>` instead of a `String`.

**Comment by lemunozm** [comment]
Yeah, is something that I had in mind. The problem with non-ascii characters is that the terminal width can differ, and the input cursor can be badly placed. It is also necessary to adapt the logic that put correctly the cursor in the input panel.
